name: Build and test
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - features/unit-tests
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-24.04
            type: ubuntu
          - os: macos-latest
            type: macos
          - os: windows-latest
            type: windows
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        if: matrix.config.type == 'windows'
        with:
          arch: x64
      - name: Install Ninja
        if: matrix.config.type == 'windows'
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install mpc
        if: matrix.config.type == 'macos'
        run: |
          brew install libmpc utf8proc ninja
      - uses: maxim-lobanov/setup-xcode@v1
        if: matrix.config.type == 'macos'
        with:
          xcode-version: latest-stable
      - name: Install mpc
        if: matrix.config.type == 'ubuntu'
        run: |
          sudo apt-get install libmpc-dev libutf8proc-dev ninja-build
      - name: Setup vcpkg
        uses: johnwason/vcpkg-action@v6
        if: matrix.config.type == 'windows'
        id: vcpkg
        with:
          pkgs: mpc utf8proc
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: true
      - name: Add vcpkg to PATH
        if: matrix.config.type == 'windows'
        env:
          VCPKG_BINARY_PATH: ${{ github.workspace }}\vcpkg\installed\x64-windows-release\bin
        run: |
          echo "$env:VCPKG_BINARY_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: tcalc
      - name: CMake Build
        uses: threeal/cmake-action@main
        with:
          generator: Ninja
          args: ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}
          build-dir: build
          source-dir: tcalc
      - name: Run Unit Tests
        run: |
          build/tests/tcalc_tests
